services:
  menu_db:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=menu'
      - 'MYSQL_PASSWORD=camilo'
      - 'MYSQL_ROOT_PASSWORD=camilo'
      - 'MYSQL_USER=acbonilla'
    ports:
      - '3306'
